name: build-latest
on:
  push:
    branches:
      - main

env:
  cr_image: ghcr.io/${{ github.repository }}

jobs:
  build-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # docker login is needed for pushing the test image
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: printenv
    - run: docker build -t ${{ env.cr_image }}:${{ github.ref_name }} .
    - run: docker tag ${{ env.cr_image }}:${{ github.ref_name }} ${{ env.cr_image }}:latest
    - run: docker push ${{ env.cr_image }}:${{ github.ref_name }}
    - run: docker push ${{ env.cr_image }}:latest

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
          az containerapp update \
          --name online-shop-app \
          --resource-group online-shop \
          --image ghcr.io/hw-iu/terminal:${{ github.ref_name }}
